### ISSUE TITLE
Rock: message not found by id

### ISSUE THREAD

**Issue by Jesn** [wechaty/puppet-services#51]
在调试过程中，自动登录进来涌进大批量消息，然后就出现下面类似情况：
```
Grpc.Core.RpcException:“
	Status(StatusCode="Aborted", Detail="{"code":27,"msg":"message not found by id 1102977905"}", 
	DebugException="Grpc.Core.Internal.CoreErrorDetailException: 
		{"created":"@1607483611.749000000",
		"description":"Error received from peer ipv4:114.215.83.32:7777",
		"file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,
		"grpc_message":
			"{	"code":27,"msg":"message not found by id 1102977905"}",
				"grpc_status":10}"
		)”
```

**Comment by Jesn** [comment]
@jcai  MessagePayloadAsync 这个方法，通过MessageId获取Message 这个方法异常

**Comment by Jesn** [comment]
@jcai  MessageFileAsync  通过MessageId获取Message 这个方法没有任何返回数据

**Comment by huan** [comment]
I ran into this issue today with our Friday BOT:

```
23:51:07 ERR VorpalIo stdout() next(START!) rejection: Error: 10 ABORTED: {"code":27,"msg":"message not found by id 2174689055"}
Error: 10 ABORTED: {"code":27,"msg":"message not found by id 2174689055"}
    at Object.exports.createStatusError (/home/friday/git/friday/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:847:24)
```

**Comment by huan** [comment]
After monitoring the log messages for about 1 hour, it seems that lots of messages will get the following error @jcai 

```
00:07:25 ERR WechatyPluginContrib ChatOps() ChatOpsPlugin(Wechaty#ckij077ys000096ooal35ak14<>(friday)) rejection: Error: 10 ABORTED: {"code":27,"msg":"message not found by id 2174690035"}
00:07:25 ERR Config ###########################
00:07:25 ERR Config unhandledRejection: Error: 10 ABORTED: {"code":27,"msg":"message not found by id 2174690037"}
    at Object.exports.createStatusError (/home/friday/git/friday/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:847:24) [object Promise]
00:07:25 ERR Config ###########################
00:07:25 ERR Config process.on(unhandledRejection) promise.catch(10 ABORTED: {"code":27,"msg":"message not found by id 2174690037"})
Config Error: 10 ABORTED: {"code":27,"msg":"message not found by id 2174690037"}
    at Object.exports.createStatusError (/home/friday/git/friday/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 10,
  metadata: Metadata {
    _internal_repr: { 'grpc-accept-encoding': [Array], 'accept-encoding': [Array] },
    flags: 0
  },
  details: '{"code":27,"msg":"message not found by id 2174690037"}'
} 
(node:13290) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 17)
```
