### ISSUE TITLE
Donut: INTERNAL: TIMEOUT, sync room timeout, room id

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-services#63]
## Wechaty Puppet Donut

- Repo: <https://github.com/juzibot/donut-tester>
- Provider: [Juzi.BOT](https://juzi.bot)
- Support: <https://github.com/juzibot/donut-tester/issues>

## Question

I got an error message as the following when I login Friday.BOT today:

```
INTERNAL: TIMEOUT, sync room timeout, room id: 17301175542@chatroom
18:54:14 ERR Config ###########################
18:54:14 ERR Config unhandledRejection: Error: 13 INTERNAL: TIMEOUT, sync room timeout, room id: 17301175542@chatroom
    at Object.exports.createStatusError (/home/friday/git/friday/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/friday/git/friday/node_modules/grpc/src/client_interceptors.js:847:24) [object Promise]
```

As I understanding, we can get the room payload from the SQLite, so I can not understand what's the reason for this timeout mean.

**Comment by InfTkm** [comment]
Error: 13 INTERNAL: TIMEOUT, sync room member timeout, room id: 18334521391@chatroom
    at Object.exports.createStatusError (/home/bitnami/StockTools/optionbot/node_modules/gr
pc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/bitnami/StockTools/optionbot/node_modules/grpc/src/cli
ent_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/bitnami/StockTools/optionbot/node_modules/grpc
/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/bitnami/StockTools/optionbot/node_module
s/grpc/src/client_interceptors.js:618:8)
    at callback (/home/bitnami/StockTools/optionbot/node_modules/grpc/src/client_intercepto
rs.js:847:24) {
  code: 13,

Experiencing similar issue. findRoom method is takes really long time.
