### ISSUE TITLE
[LongLink] socket Killed

### ISSUE THREAD

**Issue by why2lyj** [wechaty/puppet-services#99]
I'm using Python with Padlocal and based the doc https://github.com/wechaty/wechaty/discussions/1985 setup my chatbot.
but  I always got issue as followed after I logined in and chatbot will be shutdown. 

Can anyone give me  a suggestion?

```shell
02:50:21 VERB [LongLink] [e2fd82601bd246799f3494229b2eb8b1] socket recv:17f103002424f5806f21f6de1de4cfa208eb9e3543bb34fa27f282942e679c7346c7bcfcf13394c8e5
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! wechaty@0.56.6 io-client: `ts-node bin/io-client`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the wechaty@0.56.6 io-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2021-03-19T02_50_34_188Z-debug.log
```

**Comment by huan** [comment]
This is a padlocal puppet service issue, so I move to puppet-services repo.

**Comment by padlocal** [comment]
No idea after reviewing the logs, need more time to investigate.

**Comment by why2lyj** [comment]
```shell

03:03:26 VERB [Request] [tid:76c0e25f] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"82812b4ca44942be90ebc8f51392b5b1"}]}
03:03:26 VERB [Request] [tid:7f0c7bab] send event to server, seq:undefined, ack:2, type: 11, payload: {"longlinkresponse":{}}
03:03:26 VERB [Request] [tid:7f0c7bab] receive event from server, seq:0 ack:0, type:201, payload:{"status":2,"logintype":0,"qrcodeevent":{"status":0,"imageurl":"http://weixin.qq.com/x/oZGmTMq420n_Kd3T3SNJ","expireat":290}}
03:03:26 VERB [PuppetPadlocal] scan event, status: Waiting, with qrcode: http://weixin.qq.com/x/oZGmTMq420n_Kd3T3SNJ
03:03:26 INFO IoClient [2] http://weixin.qq.com/x/oZGmTMq420n_Kd3T3SNJ
Online QR Code Image: https://wechaty.js.org/qrcode/http%3A%2F%2Fweixin.qq.com%2Fx%2FoZGmTMq420n_Kd3T3SNJ
03:03:27 VERB EventStreamManager grpcEmit(EVENT_TYPE_SCAN[22], {"qrcode":"http://weixin.qq.com/x/oZGmTMq420n_Kd3T3SNJ","status":2})
03:03:34 VERB [Request] [tid:7f0c7bab] receive event from server, seq:3 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"aabbf1a6f91144a2927b03ccbff8783c","longlinkid":"","initphase":false}}
03:03:34 VERB [Request] [tid:b6ab631f] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"d76213cfd546478992f9023f88de3cab","messageid":"aabbf1a6f91144a2927b03ccbff8783c"}
03:03:34 VERB [Request] [tid:96a7fea0] receive event from server, seq:4 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"40ef68b2ad33478eae8596606e29990f","longlinkid":"","initphase":false}}
03:03:39 ERR [PuppetPadlocal] login failed: VError: [tid:96a7fea0] request has been cancelled for reason: CLIENT_ERROR: [tid:96a7fea0] Exception while handling wechat request: longlink fail to connect, host:undefined, port:undefined: longlink host port is not configured yet
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
03:03:39 VERB StateSwitch <PuppetPadlocal> off(pending) <- (false)
03:03:39 VERB [LongLink] [d76213cfd546478992f9023f88de3cab] longlink shutdown
03:03:39 VERB [LongLink] [d76213cfd546478992f9023f88de3cab] longlink stopHeartbeat
03:03:39 VERB StateSwitch <PuppetPadlocal> off(true) <- (pending)
03:03:39 VERB [Request] [tid:b6ab631f] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDAVsA/G2mod/nLnLc60urrbJQtmRQSXw8sxe+euEiPc4COcXMcUrdTY+Hejk559E7oFZ6+pbsDFqAS2rj4oMLrYbIApQo08qw8wHC5NiXJo0FR6Cn6WQt4wIdp/IVFCy4mfSR3x8UBNzRKMEqfoVwUgUKEEQXFMYy+Jl3K2L3ip7BXZkGktJG3/bUW+KM2wFBQDu1O8FskeqvaQ5LKjGTeOoLxA3JRotjFZXhk57cxNtPvuB9+XStezceRQsvQiW5+68ZGb3ZKOJZblue3/JoLe37wx+Wdl2dp70d8ZGtf4jgmMJ3Hz5FrDqGQ+Wl4h72tXzaz5m1qouihU4YmiS9mbRLIJxSRAiA0iU1a2D5A/ADCHkIjoOAqH76JVQpL62z9u9N2t2KR3ZV6AFMYF38Vq5IaoOUXsUyDY7JoWRe2JlOu+WUWn9mE9H61odQ/fjLVUqhDu///cMZMSasEA=="}
03:03:39 VERB [LongLink] [undefined] socket send:17f103015b00fc6da6a1dfe72e72dceb4babadb250b66450497c3cb317be7ae1223dce0239c5cc714add4d8f877a3939e7d13ba0567afa96ec0c5a804b6ae3e2830bad86c8029428d3cab0f301c2e4d897268d0547a0a7e9642de3021da7f215142cb899f491df1f1404dcd128c12a7e857052050a10441714c632f899772b62f78a9ec15d990692d246dff6d45be28cdb0141403bb53bc16c91eaaf690e4b2a319378ea0bc40dc9468b631595e1939edcc4db4fbee07df974ad7b371e450b2f4225b9fbaf1919bdd928e2596e5b9edff2682dedfbc31f96765d9da7bd1df191ad7f88e098c2771f3e45ac3a8643e5a5e21ef6b57cdacf99b5aa8ba2854e189a24bd99b44b209c52440880d225356b60f903f0030879088e8380a87efa2554292fadb3f6ef4ddadd8a477655e8014c605dfc56ae486a83945ec5320d8ec9a1645ed8994ebbe5945a7f6613d1fad68750fdf8cb554aa10eeffffdc3193126ac10
03:03:39 ERR Config ###########################
03:03:40 ERR Config unhandledRejection: TypeError: Cannot read property 'write' of undefined
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:173:21)
    at Generator.next (<anonymous>)
    at /wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:4:12)
    at /wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:50
    at new Promise (<anonymous>)
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:12)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) [object Promise]
03:03:40 ERR Config ###########################
03:03:40 ERR Config ###########################
03:03:40 ERR Config unhandledRejection: TypeError: Cannot read property 'write' of undefined
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:173:21)
    at Generator.next (<anonymous>)
    at /wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:4:12)
    at /wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:50
    at new Promise (<anonymous>)
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:12)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) [object Promise]
03:03:40 ERR Config ###########################
03:03:40 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'write' of undefined)
Config TypeError: Cannot read property 'write' of undefined
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:173:21)
    at Generator.next (<anonymous>)
    at /wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:4:12)
    at /wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:50
    at new Promise (<anonymous>)
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:12)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
03:03:40 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'write' of undefined)
Config TypeError: Cannot read property 'write' of undefined
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:173:21)
    at Generator.next (<anonymous>)
    at /wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:4:12)
    at /wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:50
    at new Promise (<anonymous>)
    at WeChatLongLinkProxy.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:170:12)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/padlocal-client-ts/dist/link/WeChatLongLinkProxy.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:39) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
03:03:42 VERB StateSwitch <PuppetPadlocal> on(pending) <- (false)
03:03:48 VERB [Request] [tid:72bcd066] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
03:03:49 VERB [Request] [tid:72bcd066] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"long.weixin.qq.com","port":80},"reconnectimmediately":false}}
03:03:49 VERB [Request] [tid:72bcd066] send event to server, seq:undefined, ack:1, type: 16, payload: {}
03:03:49 VERB [LongLink] [undefined] update longlink host: long.weixin.qq.com, port: 80
03:03:49 VERB [Request] [tid:72bcd066] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":0}
03:03:49 INFO [PuppetPadlocal] start login with type: QrLogin
03:03:49 VERB [Request] [tid:72bcd066] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"47e7dc29743340fe947f747e4f76260a","longlinkid":"","initphase":false}}
03:03:49 VERB [LongLink] [undefined] longlink start connect: long.weixin.qq.com:80
03:03:49 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] longlink connect success, cost 256ms
03:03:49 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] longlink start init
03:03:49 VERB [Request] [tid:670d5124] send event to server, seq:1, ack:undefined, type: 80, payload: {"longlinkid":"6dafec1a3c8b4279891648099e8f6a36"}
03:03:49 VERB [Request] [tid:670d5124] receive event from server, seq:1 ack:0, type:12, payload:{"eof":true,"longlinkrequest":{"payload":"FvEDANQAAADQAQPxAcArs9fIDt65V0xazymG6KmgUtVYKQjScgogT9CDRmN7foxgVWYVAAAAogEAAACdABACAAAARwAAAAEAQQRD7WUWy1HUV84/ZyM5V8gDEBdU398/ueeBUpk5se6igtx+kpd3Pfx2WJ25ox3IQauvFjJpQnTmJUtd0LGCzXlMAAAARwAAAAIAQQTcO9kgT70bWOmzR7aDjD/6bGCTND2+wC9+/sGDV5VrsX0ciKgLD/wm5MMkfEzpZbpCj7dGu9x4rUQq+Y4SxlCoAAAAAQ==","longlinkid":"6dafec1a3c8b4279891648099e8f6a36","initphase":true}}
03:03:49 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] socket send:16f10300d4000000d00103f101c02bb3d7c80edeb9574c5acf2986e8a9a052d5582908d2720a204fd08346637b7e8c60556615000000a2010000009d001002000000470000000100410443ed6516cb51d457ce3f67233957c803101754dfdf3fb9e781529939b1eea282dc7e9297773dfc76589db9a31dc841abaf1632694274e6254b5dd0b182cd794c0000004700000002004104dc3bd9204fbd1b58e9b347b6838c3ffa6c6093343dbec02f7efec18357956bb17d1c88a80b0ffc26e4c3247c4ce965ba428fb746bbdc78ad442af98e12c650a800000001
03:03:49 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] socket recv:16f103007b000000770203f1c02b92f2233b2f0ce4aa35715fec036bd7ecf924444a37d87ed4af30b3fab98ec6bc0000004e0100000049001100000001004104859665427f3b256e8d04cfaed26fe676901cdc016f922a5738a14052ece8e0238f06c1999e10507d3bf2b448eca61eb57d9435d44a803625339e64fe4a8a9d4e16f103005e671bf65b98e3108813fee0a87deb2b31a5d89de45bbde6f7746fbde3d7842bafc0fd9a2daee4fce29623d825ecd091fad9f7054233f5a609166b1ca9f577368107f113c01e4b9167c678be4afd2775264059529f3ea5125f85c6f894386416f10301256a3efa270a42db475ec6d7a90787c1b20f0deb86f83940745e4312e685f8454bd3ecbf29d0dd6144b301372a114f9151e85eb1c4161fd1acf33a53403493ebc1d23e9d14b77b4e36b4d942355bff106d6623ebdbf5faaf855b265328258731d0603508c8aadebb3771717d7c83ef52b81279ee19df68055cc739b953016c2e617f35226d9753ab4760acf56b01d1d6e03410a4c1b3e4fcae9ff80219848635c894de5a3bbbfecdfceded32d44c3ae9fd8829b363ab750d94e658c054fbb936174eaef3c157c7f8a4d99cd76345ca50f7be65e27ae73aab3b4f485edcc81d0b9c62522482503873fe04a21f4bd199ea8b4d3643c5dffdd5064e3625341daff07c3a9187cd82677a57f03dbbe8ad7b748f38b0eae33245e4d713263df71f76a1bae8fa90f6c116f1030037cb55c8ff52c25d07f674fac991d6038dc4b6a8f8aea670b63d97d6d79591df7f119b3f69da284dbcec5c9f49ad52b9bd6725bc9a7b5e79
03:03:49 VERB [Request] [tid:670d5124] send event to server, seq:2, ack:1, type: 13, payload: {"eof":false,"longlinkresponse":{"payload":"FvEDAHsAAAB3AgPxwCuS8iM7LwzkqjVxX+wDa9fs+SRESjfYftSvMLP6uY7GvAAAAE4BAAAASQARAAAAAQBBBIWWZUJ/OyVujQTPrtJv5naQHNwBb5IqVzihQFLs6OAjjwbBmZ4QUH078rRI7KYetX2UNdRKgDYlM55k/kqKnU4W8QMAXmcb9luY4xCIE/7gqH3rKzGl2J3kW73m93RvvePXhCuvwP2aLa7k/OKWI9gl7NCR+tn3BUIz9aYJFmscqfV3NoEH8RPAHkuRZ8Z4vkr9J3UmQFlSnz6lEl+FxviUOGQW8QMBJWo++icKQttHXsbXqQeHwbIPDeuG+DlAdF5DEuaF+EVL0+y/KdDdYUSzATcqEU+RUehescQWH9Gs8zpTQDST68HSPp0Ut3tONrTZQjVb/xBtZiPr2/X6r4VbJlMoJYcx0GA1CMiq3rs3cXF9fIPvUrgSee4Z32gFXMc5uVMBbC5hfzUibZdTq0dgrPVrAdHW4DQQpMGz5Pyun/gCGYSGNciU3lo7u/7N/O3tMtRMOun9iCmzY6t1DZTmWMBU+7k2F06u88FXx/ik2ZzXY0XKUPe+ZeJ65zqrO09IXtzIHQucYlIkglA4c/4Eoh9L0Znqi002Q8Xf/dUGTjYlNB2v8Hw6kYfNgmd6V/A9u+ite3SPOLDq4zJF5NcTJj33H3ahuuj6kPbBFvEDADfLVcj/UsJdB/Z0+smR1gONxLao+K6mcLY9l9bXlZHffxGbP2naKE287FyfSa1Sub1nJbyae155"}}
03:03:49 VERB [Request] [tid:670d5124] receive event from server, seq:0 ack:2, type:14, payload:{"eof":true,"longlinkresponsereply":{"payload":"FvEDADeQxSJU8sao/K3zihzKouDoFN0qGciLa8B2aeSaX4Gk7Rh/nUiu7hSAhkYOLXaHLJ47ghqWSRNO"}}
03:03:49 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] socket send:16f103003790c52254f2c6a8fcadf38a1ccaa2e0e814dd2a19c88b6bc07669e49a5f81a4ed187f9d48aeee148086460e2d76872c9e3b821a9649134e
03:03:49 VERB [Request] [tid:670d5124] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"74816185f1df4a81b36da907b3425abd","longlinkid":"6dafec1a3c8b4279891648099e8f6a36","initphase":true}}
03:03:49 VERB [Request] [tid:60c14d4d] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"6dafec1a3c8b4279891648099e8f6a36","messageid":"74816185f1df4a81b36da907b3425abd"}
03:03:49 VERB [Request] [tid:60c14d4d] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDACD+N69lSfvvPvDYBPLlZStPZ2FPHTZQSqbmHUKwPDFnhA=="}
03:03:49 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] socket send:17f1030020fe37af6549fbef3ef0d804f2e5652b4f67614f1d36504aa6e61d42b03c316784
03:03:50 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] socket recv:17f10300201a260f905b878ea80a9e664373c8068ad4cefedae4def0b31ca204e9b98b82ee
03:03:50 VERB [Request] [tid:9491b3a9] send event to server, seq:1, ack:undefined, type: 84, payload: {"longlinkid":"6dafec1a3c8b4279891648099e8f6a36","payload":"F/EDACAaJg+QW4eOqAqeZkNzyAaK1M7+2uTe8LMcogTpuYuC7g=="}
03:03:50 VERB [Request] [tid:9491b3a9] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"74816185f1df4a81b36da907b3425abd"}]}
03:03:50 VERB [Request] [tid:670d5124] send event to server, seq:undefined, ack:2, type: 11, payload: {"longlinkresponse":{}}
03:03:50 VERB [Request] [tid:670d5124] receive event from server, seq:0 ack:1, type:81, payload:{}
03:03:50 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] longlink init done, cost 904ms
03:03:50 VERB [Request] [tid:1f49dd72] send event to server, seq:1, ack:undefined, type: 82, payload: {"longlinkid":"6dafec1a3c8b4279891648099e8f6a36","messageid":"47e7dc29743340fe947f747e4f76260a"}
03:03:50 VERB [Request] [tid:1f49dd72] receive event from server, seq:0 ack:1, type:83, payload:{"payload":"F/EDAj89Y+AW8+NEJMQ5Rv5XFbUFyP4AIpd7xpUMGFczRnhz7yeVQEmDsObKIiVQ9WSPd038QZrfMIZLMeUThMnA/oduhWqtIQsjmrVxvenecqs+RneEn13Dlzr3XTcgJ89+yPsfiKePz7wpsIH3YqHrPIXjCQMzr0tQU4+k4b2Zczf4v5AVphofPbh5w70oMwqStKQo0PoFzqd2OaWkhg/T3x4LlZUQbjTY3309yzWZn494awJSMkrlE07P8KZTVuUPHG+QcNt6COPylDdDkdiXU31xNHslxSlLAmRP8k0zd1b8vAf0m4giVPxFbrIWhn6TPdAEQPxIoywIqP6cIxnXnQWJPrUC4gmB1a2ipaOgK8yY8+S9RF17eYhrj1p9aT4XLifi/+7ZZiDq4goU6mrAKGcU3+SXGN1MDpEc6xzMsaOmUn1F16HDShYWA9cp2W4amv6BJH+WJ7oPUAbAIosiwlx1y9gghgwQQ81m4oK/H/cg/DnNfc+IvdCKECKUlUGTdMCsFjmDl3NIy8Y7PatnSBDyn0Un5M8nDIxk1+0uRbfgbGs1IWWpieSf4/wPAlFSpD4Sx3O4JGEzgaLDFyG2s4resVbHtbv5ruejzoKLsVPGbZxGyt7o2xVcHe7Zwr/cZNIuyqnwNcHV0CC5mjHrTjj7wWSSCCFJB9jthUlG9HaJM53bl923OLE2r53ciBeoABowxvWS8jZ38VvKDPsqVaatJT0syXKRJXn18GO3YNQN+ZgxgP9+IpomZPqgwH02tw=="}
03:03:50 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] socket send:17f103023f3d63e016f3e34424c43946fe5715b505c8fe0022977bc6950c185733467873ef2795404983b0e6ca222550f5648f774dfc419adf30864b31e51384c9c0fe876e856aad210b239ab571bde9de72ab3e4677849f5dc3973af75d372027cf7ec8fb1f88a78fcfbc29b081f762a1eb3c85e3090333af4b50538fa4e1bd997337f8bf9015a61a1f3db879c3bd28330a92b4a428d0fa05cea77639a5a4860fd3df1e0b9595106e34d8df7d3dcb35999f8f786b0252324ae5134ecff0a65356e50f1c6f9070db7a08e3f294374391d897537d71347b25c5294b02644ff24d337756fcbc07f49b882254fc456eb216867e933dd00440fc48a32c08a8fe9c2319d79d05893eb502e20981d5ada2a5a3a02bcc98f3e4bd445d7b79886b8f5a7d693e172e27e2ffeed96620eae20a14ea6ac0286714dfe49718dd4c0e911ceb1cccb1a3a6527d45d7a1c34a161603d729d96e1a9afe81247f9627ba0f5006c0228b22c25c75cbd820860c1043cd66e282bf1ff720fc39cd7dcf88bdd08a10229495419374c0ac163983977348cbc63b3dab674810f29f4527e4cf270c8c64d7ed2e45b7e06c6b352165a989e49fe3fc0f025152a43e12c773b824613381a2c31721b6b38adeb156c7b5bbf9aee7a3ce828bb153c66d9c46cadee8db155c1deed9c2bfdc64d22ecaa9f035c1d5d020b99a31eb4e38fbc1649208214907d8ed854946f47689339ddb97ddb738b136af9ddc8817a8001a30c6f592f23677f15bca0cfb2a55a6ad253d2cc972912579f5f063b760d40df9983180ff7e229a2664faa0c07d36b7
03:03:50 VERB [LongLink] [6dafec1a3c8b4279891648099e8f6a36] socket recv:17f10341870d8141b3be4cfae817c159b0d799935c7c970945ed9162f85665833bf5141ad433d19d8fbf126c7e2de9bb5b49c114e50fa3b6716eabcc9676489d2698c2958480b26426bc31bbaeb03d6d0dc2abf8d758594deea71a875046945196242ac8cf4e51bd0323ae914c178ddb50186737293771482547afdc917636f6dc0964e1c6e6ec5824cbddeee3709817804ac287d1980165fa62198e82242e5803a4800f9f344c9c23fc5c2f252f42a5a61ae3f7e96563e30cca24cbd0bcf4f5773271bfe18a8612f7a81761175d1501f01b67d32a3caabbba537ae2a104c0e1ea2bd93f17c2b67a47a7f5e228eb5cf68dcd4fc22b97f388bd382567e8e6f64290f63881f23b5a186647eb641540b49de882e3c5335f0e395d6e0885efb128c4500e84029b440a1f8b1d3ca1cd49f9b7a5b5f25cae74bdc5040fead110ee2744688619f2e6717492dfe629dec8da5e940391d704419b0ca55de0209948a9b5f7202fd85163f09b652588b995385ada58cb97f64f2a7b42729504e1c9e310865b5384fb01ef06f521f9c4127ad8def875b631f23a12ec06aff9e7c13351b552bb3e9a66ad29e7ccd9aa9852c79cb837539b4fb0069195182b07c95d58013c542a892868da0ac334a569fbc713f6d85cffb5c2172ec038af8e8df6b5ce628517b3488d1d6723315349e5469824f33cd9f65f736c043bb045be32cc94012dc73f2fef426a549898e64049cccbd06a4d0c5ee25ac58591435495b70bf181b82c7105af63f3da7c3d473c5caf308d14a3da1a68690eac5f94437588d76205ad29de9dae253e4bfb05d4ac6d083d211b443556fc8d957db83145fe5e59fdc22cc890ac1936e47a4c9e0ce01e3aeb8ef1c36d60df2636943f76116a54d220f1baddf615200b736577d2aeb49c46ac80c95448d7cdb8f7a0cdd44327cf4ab7c165447b37b9c963c07b1e20e71ac2426ec5fe91786149e8bb214e8d03cc85a2bb8a4d2d765c1ac4af4877b1cbcdce104502c47bf5b83d8a2c64ebfef10078cc4f79a1b2a864cbfecda3e5b8f46234fed04c17baf1296a6abf7a9a6006431347e227cb8b7eb20c07507cd6b33ad0b03832ba0cc91582db79c7347dd2141c2d67021ad187bca59a987d7b237fef7b2659e714a44c3fe4e0d9631c42fcd68c8110dbbf3c7cee20ab607d76078bdedaa9459e4c3e6d01907703f767fad40264c6b2b0bc74907a4be32823435a2fe9026ad5e857a1e3b304aac74e5544870b21c8dd4d7f1877210893c88d5b5ed2a6660cc89d65550678020af1fe675eb05f9e2536083a58cc495ea3fe477b433ee59a5e6ea6e198adb9ddd25ca308ca68db8d55e55a664fce37e27ed16066df664a1ee489b0e450a0b63074df4eca4f7f70f166ab7fe2a275cc41e75e59f27156963ec9234935f7a3900483e20c3bfb6d754e26abfeb95a310b0ead127904a1aab3ce917ae9ba6ec4e4a4f33f91b13b7042912cc899bc79c79255f536a1b30c380245224ac0842dbcaf334dd8884efca40212b3fcab23df8218358eab3cfaf4a74b516ef1fa6fc927e74e8f9ceb306f0b14716eb21de2eeb32ea5b58179ef624d51e290fc3d24d754e5676b46933a502133e4ba894786f2a70b74eaad036744554a1c448bf7927b8074fa978d3ebc7ee596a3647846192813b983534debd08a36d8c8b017ae2b53655c0453733fe647432431d18dcb306963d8184411fb1c2b1adb75ed3b8dc9b80051a83617c0ef5b938397dad8bc1d6914043cc544334a984c3c96155f7b301dae1657371fab2572ddfe4cde7adab0c87c869d51ed82504715b195c82314839eb128408466b0d8a28e64f318849fa787670cf937bc0f0969402aabde7e0b9d1bbe9c423b78f33a65024de93498fcc50e9a8f9d2dc5376c39670d3ebcec1c83b5f0300081338330436b89f79016faac0e6716776b06b1e540674e3f9ee1d6a8261313854c69dff98a2b6780a67e6fb72157a891c7b7d263dc3072413f409b57dee54e358148440b95bbb9c1d080d37d1cbe4eeae824a65acab0423b5258fd7e4ed9a3a2b2a3e2cf94f05602911d9d73607bf66e8be2cedcdcf774a1950a862bf181f438861ac0b7fcedb9039eba4a30d697c793b1e652b00722a77a2f2be5373fe5053e26e4b5e49b98fe14d3b24a507dea6f6ac02e0f354335cf89f30dcf2504f47d6b6f58bde2b20ee92ece399a55a878b4d21fb3372660c127c25e68585c4d09009c02e46cf670d74039add6c095ca85c9639c18cb4dbe1b6244674cc464ee0a3b45fd980c41fe7f68eb353715c05857798bdf5aa7087ef229bb61ff006ac2e48291d4fd6eebc5afa04261d0dc99826987ecf2c928da8cbcd75ba5c032f9a1327bb5a633ab8ce556bbeaae553a34411e1ff1db60ac64a4215ff59d6d828528c2b565b46110ceb5efff8b3179f2f83a87f3cd956afa56400ca82e29cc17520d8983ff9c5a89001f95abb8a8128b44045694c6ed0a0bebd9e4dced48f655c29be9e67157803a3ccb04454f7a218b46c28a7ba2430696aab672adacfa2b3102e89cbcfc6ccdb949b3d76f4fc3ad596daf830d1612924de7b5c32d9835ce4115a79ceffd0eb1033fee7fdd6ae59d3ba437d24a6f57081a6a81e49fcced902d445344694b6b41778dda5c3d21d573fbb363be083ec9185a866f04c94e8e6ab5340f13edb524036ef755d1538882463095a87998b912073ecba38313e8be031669411e7a4ee217289f5ab46c4445a6858a568c389adb64f0bdd8a01dadb05384b8ac53546f6b5241ed772284632ce53d907688161307da8bc14de70c8f12a47de77e39f5b222b1c8813172cf216b408474b5e34b83e1601944a16d195066dd258a38ec4d77a231a3cc3093868a61235bfde9f878[TRUNCATED:12192]

```

**Comment by why2lyj** [comment]
```shell

Starting Docker Container for Wechaty v0.56.6 with Node.js v12.20.1 ...
   ____ _           _   _        _
  / ___| |__   __ _| |_(_) ___  (_) ___
 | |   | '_ \ / _` | __| |/ _ \ | |/ _ \
 | |___| | | | (_| | |_| |  __/_| | (_) |
  \____|_| |_|\__,_|\__|_|\___(_)_|\___/

     _         _   _     _               ____
    / \  _   _| |_| |__ (_)_ __   __ _  | __ ) _   _ _
   / _ \| | | | __| '_ \| | '_ \ / _` | |  _ \| | | (_)
  / ___ \ |_| | |_| | | | | | | | (_| | | |_) | |_| |_
 /_/   \_\__,_|\__|_| |_|_|_| |_|\__, | |____/ \__, (_)
                                 |___/         |___/

WECHATY_TOKEN=local_service_fd32eda97eda8ea

/wechaty ~

> wechaty@0.56.6 io-client /wechaty
> ts-node bin/io-client

03:02:47 INFO Config registering process.on("unhandledRejection") for development/debug
03:02:47 VERB Config constructor()
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! wechaty@0.56.6 io-client: `ts-node bin/io-client`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the wechaty@0.56.6 io-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2021-03-24T03_03_04_961Z-debug.log
```

**Comment by why2lyj** [comment]
@padlocal  Is there any progress?
